# Generated by Django 3.1.4 on 2021-01-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs', 'Mrs'), ("Ma'am", "Ma'am"), ('Sir', 'Sir'), ('Ms', 'Ms')], max_length=60),
        ),
    ]
