# Generated by Django 3.1.4 on 2021-01-02 03:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210101_1926'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profiles',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms', 'Ms'), ('Sir', 'Sir'), ("Ma'am", "Ma'am"), ('Mrs', 'Mrs')], max_length=60),
        ),
    ]
