# Generated by Django 3.1.4 on 2021-01-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210101_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr.', 'Mr.'), ("Ma'am", "Ma'am"), ('Sir', 'Sir')], max_length=60),
        ),
    ]
