# Generated by Django 3.1.4 on 2021-01-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210103_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[("Ma'am", "Ma'am"), ('Sir', 'Sir'), ('Mr.', 'Mr.'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], max_length=60),
        ),
    ]
