# Generated by Django 3.1.4 on 2021-01-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210103_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[("Ma'am", "Ma'am"), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mr.', 'Mr.'), ('Sir', 'Sir')], max_length=60),
        ),
    ]
