# Generated by Django 3.1.4 on 2021-01-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210105_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ("Ma'am", "Ma'am"), ('Ms', 'Ms'), ('Sir', 'Sir'), ('Mr.', 'Mr.')], max_length=60),
        ),
    ]
