# Generated by Django 3.1.4 on 2021-01-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210105_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[("Ma'am", "Ma'am"), ('Sir', 'Sir'), ('Mr.', 'Mr.'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=60),
        ),
    ]
