# Generated by Django 3.1.4 on 2021-01-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210105_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Sir', 'Sir'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ("Ma'am", "Ma'am"), ('Mr.', 'Mr.')], max_length=60),
        ),
    ]
