# Generated by Django 3.1.4 on 2021-01-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210105_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs', 'Mrs'), ("Ma'am", "Ma'am"), ('Ms', 'Ms'), ('Sir', 'Sir')], max_length=60),
        ),
    ]
