# Generated by Django 3.1.4 on 2021-01-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210105_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Ms', 'Ms'), ("Ma'am", "Ma'am"), ('Mr.', 'Mr.'), ('Sir', 'Sir'), ('Mrs', 'Mrs')], max_length=60),
        ),
    ]
