# Generated by Django 3.1.4 on 2021-01-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210105_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ("Ma'am", "Ma'am"), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Sir', 'Sir')], max_length=60),
        ),
    ]
