# Generated by Django 3.1.4 on 2021-01-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210105_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Sir', 'Sir'), ('Ms', 'Ms'), ('Mr.', 'Mr.'), ('Mrs', 'Mrs'), ("Ma'am", "Ma'am")], max_length=60),
        ),
    ]
