# Generated by Django 3.1.4 on 2021-01-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20210105_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ("Ma'am", "Ma'am"), ('Sir', 'Sir')], max_length=60),
        ),
    ]
