# Generated by Django 3.1.4 on 2021-01-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20210105_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mr.', 'Mr.'), ("Ma'am", "Ma'am"), ('Sir', 'Sir')], max_length=60),
        ),
    ]
