# Generated by Django 3.1.4 on 2021-01-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210105_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Sir', 'Sir'), ('Mr.', 'Mr.')], max_length=60),
        ),
    ]
