# Generated by Django 3.1.4 on 2021-01-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20210105_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Sir', 'Sir'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=60),
        ),
    ]
