# Generated by Django 3.1.4 on 2021-01-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20210105_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Sir', 'Sir'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mr.', 'Mr.')], max_length=60),
        ),
    ]
