# Generated by Django 3.1.4 on 2021-01-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20210107_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Sir', 'Sir'), ('Mr.', 'Mr.'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=60),
        ),
    ]
