# Generated by Django 3.1.4 on 2021-01-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20210107_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mr.', 'Mr.'), ('Sir', 'Sir'), ('Mrs', 'Mrs')], max_length=60),
        ),
    ]
