# Generated by Django 3.1.4 on 2021-01-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20210107_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms', 'Ms'), ('Sir', 'Sir'), ('Mrs', 'Mrs')], max_length=60),
        ),
    ]
