# Generated by Django 3.1.5 on 2021-01-09 01:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=60)),
                ('Course_Number', models.IntegerField(blank=True, default='')),
                ('Instructor_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Duration', models.FloatField(blank=True, default='')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
